package block1.cc.dfa;

import java.util.ArrayList;
import java.util.List;

public class MyScanner implements Scanner{
    /**
     * Returns the list of tokens generated by a given DFA when scanning a given
     * input text; or <code>null</code> if the input text is not accepted.
     * Scanning is greedy; i.e., it should always return the longest acceptable
     * token.
     *
     * @param dfa
     * @param text
     */
    @Override
    public List<String> scan(State dfa, String text) {
        State startState = dfa;
        ArrayList<String> tokens = new ArrayList<>();
        int i = 0;
        int lastValidTokenIndex = 0;

        while (i < text.length() && dfa.hasNext(text.charAt(i))) {
            dfa = dfa.getNext(text.charAt(i));
            i++;
            if (dfa.isAccepting()) {
                lastValidTokenIndex = i;
            }
            // if in error state and a token was found
            if (!(i < text.length() && dfa.hasNext(text.charAt(i))) && lastValidTokenIndex != 0) {
                tokens.add(text.substring(0, lastValidTokenIndex));
                text = text.substring(lastValidTokenIndex);
                dfa = startState;
                i = 0;
                lastValidTokenIndex = 0;
            }
        }
        return tokens;
    }
}
